### PR TITLE
Fixed problem with wp_logout returning HTML

### PR DESCRIPTION
**Pull request by morgenhaar**
The wp_logout-function returned html, so the "Success" or "Error"-prompt wouldn't show up
Also added a "General Error"-prompt to ajax-function

### CODE REVIEW

**Comment by renventura** [comment]
Thanks for the contribution, @morgenhaar!

Were you able to see what HTML the `wp_logout()` function was returning. That function doesn't actually return a value, so I'd be curious to know a bit more about what was going on there.

Also, is there a particular reason for changing the AJAX from `$.post()` to `$.ajax()`?

**Comment by morgenhaar** [comment]
@renventura 

The `wp_logout()` would navigate the user back to the front page, which meant that it ended up returning the entire front page as HTML and thereby never getting to the deleting-part of the script 

`$.ajax()` is just straight up easier to debug 😄

**Comment by renventura** [comment]
Works for me! Thanks for your work, @morgenhaar. 😁

**Comment by morgenhaar** [comment]
Thank you for the plugin! ☺️

**Pull request merged**
